highlighter: pygments
pygments:    true
markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


# Permalinks
#permalink:        pretty

title:            Лекции по курсу «Языки программирования» 2014
tagline:          ФИИТ на Мехмате ЮФУ
baseurl:          /PL_Lections_2014-2015/
ghurl:			  https://github.com/razykov/PL_Lections_2014-2015/
